#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check prettier styling
yarn check-format || 

(
    echo '🤢🤮🤢🤮 Its F**KING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
            Prettier Check Failed. Run yarn format, add changes and try commit again.';
    false;
)


#Check eslint
yarn lint || 

(
    echo '😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤 
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

echo '🤔🤔🤔🤔... Alright... Code looks good to me... 🤔🤔🤔🤔'


yarn pre-commit

echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'